In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix




In [2]:
#reading the dataset 

dataset = pd.read_csv('spam.csv')

In [3]:
dataset.head()

word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
0            0.00               0.64           0.64           0.0   
1            0.21               0.28           0.50           0.0   
2            0.06               0.00           0.71           0.0   
3            0.00               0.00           0.00           0.0   
4            0.00               0.00           0.00           0.0   

   word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
0           0.32            0.00              0.00                0.00   
1           0.14            0.28              0.21                0.07   
2           1.23            0.19              0.19                0.12   
3           0.63            0.00              0.31                0.63   
4           0.63            0.00              0.31                0.63   

   word_freq_order  word_freq_mail  ...  char_freq_;  char_freq_(  \
0             0.00            0.00  ...         0.00        0.000   
1             0.00            0.94  ...         0.00        0.132   
2             0.64            0.25  ...         0.01        0.143   
3             0.31            0.63  ...         0.00        0.137   
4             0.31            0.63  ...         0.00        0.135   

   char_freq_[  char_freq_!  char_freq_$  char_freq_#  \
0          0.0        0.778        0.000        0.000   
1          0.0        0.372        0.180        0.048   
2          0.0        0.276        0.184        0.010   
3          0.0        0.137        0.000        0.000   
4          0.0        0.135        0.000        0.000   

   capital_run_length_average  capital_run_length_longest  \
0                       3.756                          61   
1                       5.114                         101   
2                       9.821                         485   
3                       3.537                          40   
4                       3.537                          40   

   capital_run_length_total  spam_or_not  
0                       278            1  
1                      1028            1  
2                      2259            1  
3                       191            1  
4                       191            1  

[5 rows x 58 columns]

In [4]:
# dataset.info()

In [5]:
# dataset.describe()

In [6]:
#split the dataset into training data and testing data 
# X =  lables
# y = tagret variable 
X = dataset.iloc[:,0:57]
y = dataset.iloc[:,57:]
X


word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
0               0.00               0.64           0.64           0.0   
1               0.21               0.28           0.50           0.0   
2               0.06               0.00           0.71           0.0   
3               0.00               0.00           0.00           0.0   
4               0.00               0.00           0.00           0.0   
...              ...                ...            ...           ...   
4596            0.31               0.00           0.62           0.0   
4597            0.00               0.00           0.00           0.0   
4598            0.30               0.00           0.30           0.0   
4599            0.96               0.00           0.00           0.0   
4600            0.00               0.00           0.65           0.0   

      word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
0              0.32            0.00              0.00                0.00   
1              0.14            0.28              0.21                0.07   
2              1.23            0.19              0.19                0.12   
3              0.63            0.00              0.31                0.63   
4              0.63            0.00              0.31                0.63   
...             ...             ...               ...                 ...   
4596           0.00            0.31              0.00                0.00   
4597           0.00            0.00              0.00                0.00   
4598           0.00            0.00              0.00                0.00   
4599           0.32            0.00              0.00                0.00   
4600           0.00            0.00              0.00                0.00   

      word_freq_order  word_freq_mail  ...  word_freq_conference  char_freq_;  \
0                0.00            0.00  ...                   0.0        0.000   
1                0.00            0.94  ...                   0.0        0.000   
2                0.64            0.25  ...                   0.0        0.010   
3                0.31            0.63  ...                   0.0        0.000   
4                0.31            0.63  ...                   0.0        0.000   
...               ...             ...  ...                   ...          ...   
4596             0.00            0.00  ...                   0.0        0.000   
4597             0.00            0.00  ...                   0.0        0.000   
4598             0.00            0.00  ...                   0.0        0.102   
4599             0.00            0.00  ...                   0.0        0.000   
4600             0.00            0.00  ...                   0.0        0.000   

      char_freq_(  char_freq_[  char_freq_!  char_freq_$  char_freq_#  \
0           0.000          0.0        0.778        0.000        0.000   
1           0.132          0.0        0.372        0.180        0.048   
2           0.143          0.0        0.276        0.184        0.010   
3           0.137          0.0        0.137        0.000        0.000   
4           0.135          0.0        0.135        0.000        0.000   
...           ...          ...          ...          ...          ...   
4596        0.232          0.0        0.000        0.000        0.000   
4597        0.000          0.0        0.353        0.000        0.000   
4598        0.718          0.0        0.000        0.000        0.000   
4599        0.057          0.0        0.000        0.000        0.000   
4600        0.000          0.0        0.125        0.000        0.000   

      capital_run_length_average  capital_run_length_longest  \
0                          3.756                          61   
1                          5.114                         101   
2                          9.821                         485   
3                          3.537                          40   
4                          3.537              

In [7]:
y.shape

(4601, 1)

In [8]:
#splitting the dataset into training  (80%)  and testing (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state = 1)

In [9]:

#applying the MLP SVM 
# with rbf kernel
# C = 1000 for 1000 we are getting good Accuracy
# accuracy 90%
# for i in range(10,1000,10):
#     svmclf = svm.SVC(C=200, kernel='rbf', gamma='scale',)
#     svmclf.fit(X_train, y_train)
#     y_pred = svmclf.predict(X_test)
#     cm = confusion_matrix( y_pred, y_test)
#     TN=cm[0][0]
#     FN=cm[1][0]
#     TP=cm[1][1]
#     FP=cm[0][1]
#     accuracy=(TN+TP)/(TN+TP+FN+FP)
#     precision=(TP)/(TP+FP)
#     recall=TP/(TP+FN)
#     print(accuracy,i)

In [10]:
#applying the MLP SVM 
# with rbf kernel
# C = 1000 
# accuracy 90%
svmclf = svm.SVC(C=1000, kernel='rbf', gamma='scale',)
svmclf.fit(X_train, y_train)
y_pred = svmclf.predict(X_test)

/home/umer/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [11]:
#comparing the predicted value with actual value
y_test=y_test.to_numpy()
pa = pd.DataFrame({'Actual': y_test.flatten(), 'Predicted': y_pred.flatten()})
print(pa)

     Actual  Predicted
0         1          0
1         1          0
2         1          1
3         0          0
4         0          0
..      ...        ...
916       0          0
917       0          0
918       0          0
919       0          0
920       0          0

[921 rows x 2 columns]


In [12]:
#comfusion martix for finding the accuracy
cm = confusion_matrix( y_pred, y_test)
print("confusion matrix")
print(cm)

confusion matrix
[[533  56]
 [ 31 301]]


In [13]:
TN=cm[0][0]
FN=cm[1][0]
TP=cm[1][1]
FP=cm[0][1]
accuracy=(TN+TP)/(TN+TP+FN+FP)
precision=(TP)/(TP+FP)
recall=TP/(TP+FN)

print('Accuracy: ',accuracy,'\nPrecision:',precision,'\nRecall:',recall)

Accuracy:  0.9055374592833876 
Precision: 0.8431372549019608 
Recall: 0.9066265060240963


In [14]:
#smv with linear kaernal
# C = 1000 wr are getting 82% accuracy 
# ac = 0

#we are using the for loop to find the vlaue of C 
# for i in range(10,1000,10):
    
#     svmlclf = svm.LinearSVC(C=i)

#     svmlclf.fit(X_train, y_train)
#     y_pred = svmlclf.predict(X_test)
    
#     cm = confusion_matrix( y_pred, y_test)
#     TN=cm[0][0]
#     FN=cm[1][0]
#     TP=cm[1][1]
#     FP=cm[0][1]
#     accuracy=(TN+TP)/(TN+TP+FN+FP)
#     precision=(TP)/(TP+FP)
#     recall=TP/(TP+FN)
#     ac = max(ac,accuracy)
#     print(ac,i)


In [40]:
#smv with linear kaernal
# C = 1000 wr are getting 88% accuracy
svmlclf = svm.LinearSVC(C=1000)
svmlclf.fit(X_train, y_train)
y_pred = svmlclf.predict(X_test)


/home/umer/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/umer/.local/lib/python3.6/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [41]:
# y_test=y_test.to_numpy()

In [42]:
pa = pd.DataFrame({'Actual': y_test.flatten(), 'Predicted': y_pred.flatten()})
print(pa)

     Actual  Predicted
0         1          0
1         1          0
2         1          1
3         0          0
4         0          0
..      ...        ...
916       0          0
917       0          0
918       0          0
919       0          0
920       0          0

[921 rows x 2 columns]


In [43]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix( y_pred, y_test)
print("confusion matrix")
print(cm)

confusion matrix
[[522  60]
 [ 42 297]]


In [44]:
TN=cm[0][0]
FN=cm[1][0]
TP=cm[1][1]
FP=cm[0][1]
accuracy=(TN+TP)/(TN+TP+FN+FP)
precision=(TP)/(TP+FP)
recall=TP/(TP+FN)

print('Accuracy: ',accuracy,'\nPrecision:',precision,'\nRecall:',recall)

Accuracy:  0.8892508143322475 
Precision: 0.8319327731092437 
Recall: 0.8761061946902655


In [20]:
#svm with Quadratic kernel
# Polynomial Kernel of degree 2 is nothing but Quadratic kernel 
#C = 1000 wr are getting 77% accuracy
#
# for i in range(10,1000,10):
#     svmclf = svm.SVC(C=1000, kernel='poly', degree=2, gamma='scale',)
#     svmclf.fit(X_train, y_train)
#     y_pred = svmclf.predict(X_test)
#     cm = confusion_matrix( y_pred, y_test)
#     TN=cm[0][0]
#     FN=cm[1][0]
#     TP=cm[1][1]
#     FP=cm[0][1]
#     accuracy=(TN+TP)/(TN+TP+FN+FP)
#     print(accuracy,i)

In [21]:
#svm with Quadratic kernel
# Polynomial Kernel of degree 2 is nothing but Quadratic kernel 
#C = 1000 wr are getting 77% accuracy
svmclf = svm.SVC(C=1000, kernel='poly', degree=2, gamma='scale',)
svmclf.fit(X_train, y_train)
y_pred = svmclf.predict(X_test)

/home/umer/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [22]:
#comparing the predicted value with actual value
# y_test=y_test.to_numpy()
pa = pd.DataFrame({'Actual': y_test.flatten(), 'Predicted': y_pred.flatten()})
print(pa)

     Actual  Predicted
0         1          0
1         1          0
2         1          0
3         0          0
4         0          0
..      ...        ...
916       0          0
917       0          0
918       0          0
919       0          0
920       0          0

[921 rows x 2 columns]


In [23]:
cm = confusion_matrix( y_pred, y_test)
print("confusion matrix")
print(cm)

confusion matrix
[[552 193]
 [ 12 164]]


In [24]:
TN=cm[0][0]
FN=cm[1][0]
TP=cm[1][1]
FP=cm[0][1]
accuracy=(TN+TP)/(TN+TP+FN+FP)
precision=(TP)/(TP+FP)
recall=TP/(TP+FN)
print('Accuracy: ',accuracy,'\nPrecision:',precision,'\nRecall:',recall)

Accuracy:  0.7774158523344191 
Precision: 0.45938375350140054 
Recall: 0.9318181818181818
